--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JeroGamingYT-pm-pl/SimpleFly
build-by-default: true
branches:
- pm4
- pm5
projects:
  SimpleFly:
    path: ""
    icon: icon.png
...
