name: SimpleFly
version: 0.0.3
api: 5.0.0
main: YTBJero\SimpleFly\Main 
author: YTBJero

commands:
  fly:
    permission: simplefly.command 
    description: "Fly mode"

permissions:
  simplefly.command:
    description: "Fly mode"
    default: op